// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vilanova.Infrastructure.Data;

namespace Vilanova.Infrastructure.Migrations
{
    [DbContext(typeof(VilanovaContext))]
    [Migration("20181116205242_FistStartProject")]
    partial class FistStartProject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vilanova.ApplicationCore.Entities.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasMaxLength(150);

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnName("SobreNome")
                        .HasMaxLength(150);

                    b.HasKey("id");

                    b.ToTable("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
