// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vilanova.Infrastructure.Data;

namespace Vilanova.Infrastructure.Migrations
{
    [DbContext(typeof(VilanovaContext))]
    [Migration("20190325183218_Criar_Database")]
    partial class Criar_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vilanova.Domain.Entities.Contato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ContatoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(255);

                    b.Property<int>("PessoaId");

                    b.Property<int>("TipoContatoId")
                        .HasColumnName("TipoContatoId");

                    b.HasKey("id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoContatoId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("Vilanova.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("EnderecoId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnName("Bairro")
                        .HasMaxLength(255);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasMaxLength(255);

                    b.Property<int>("PessoaId");

                    b.HasKey("id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Vilanova.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PessoaId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnName("Cpf")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataCadastro");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome")
                        .HasMaxLength(255);

                    b.Property<string>("Rg")
                        .HasColumnName("Rg")
                        .HasMaxLength(8);

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasColumnName("SobreNome")
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Vilanova.Domain.Entities.TipoContato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnName("Descricao")
                        .HasMaxLength(255);

                    b.HasKey("id")
                        .HasName("TipoContato");

                    b.ToTable("TipoContatos");
                });

            modelBuilder.Entity("Vilanova.Domain.Entities.Contato", b =>
                {
                    b.HasOne("Vilanova.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Vilanova.Domain.Entities.TipoContato", "TipoContato")
                        .WithMany("Contatos")
                        .HasForeignKey("TipoContatoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Vilanova.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("Vilanova.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
